import globals from 'globals';

export default [
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: 'module',
      globals: {
        ...globals.node,
        process: 'readonly',
        Buffer: 'readonly',
      },
    },
    rules: {
      // ==================== POSSIBLE ERRORS ====================
      'no-console': ['warn'],
      'no-debugger': 'error',
      'no-dupe-args': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': ['error', { allowEmptyCatch: false }],
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-extra-semi': 'error',
      'no-func-assign': 'error',
      'no-import-assign': 'error',
      'no-inner-declarations': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-obj-calls': 'error',
      'no-promise-executor-return': 'warn',
      'no-prototype-builtins': 'warn',
      'no-setter-return': 'error',
      'no-sparse-arrays': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',

      // ==================== BEST PRACTICES ====================
      'array-callback-return': 'error',
      'block-scoped-var': 'error',
      curly: ['error', 'all'],
      'dot-location': ['error', 'property'],
      'dot-notation': 'warn',
      eqeqeq: ['error', 'always'],
      'no-alert': 'warn',
      'no-case-declarations': 'error',
      'no-else-return': 'warn',
      'no-empty-function': ['warn', { allow: ['arrowFunctions'] }],
      'no-empty-pattern': 'error',
      'no-eq-null': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-fallthrough': 'error',
      'no-floating-decimal': 'error',
      'no-global-assign': 'error',
      'no-implicit-coercion': 'error',
      'no-implied-eval': 'error',
      'no-invalid-this': 'warn',
      'no-iterator': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-loop-func': 'error',
      'no-multi-spaces': 'error',
      'no-multi-str': 'error',
      'no-new': 'warn',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-octal': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': ['warn', { props: false }],
      'no-proto': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-return-assign': 'error',
      'no-return-await': 'error',
      'no-script-url': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-throw-literal': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unused-expressions': 'error',
      'no-unused-labels': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-useless-return': 'error',
      'no-void': 'error',
      'no-with': 'error',
      'prefer-promise-reject-errors': 'error',
      'prefer-regex-literals': 'warn',
      radix: 'warn',
      'require-await': 'warn',
      'wrap-iife': ['error', 'inside'],
      yoda: ['error', 'never'],

      // ==================== VARIABLES ====================
      'init-declarations': 'off',
      'no-catch-shadow': 'error',
      'no-delete-var': 'error',
      'no-label-var': 'error',
      'no-shadow': ['warn', { builtinGlobals: false, hoist: 'all' }],
      'no-shadow-restricted-names': 'error',
      'no-undef': ['error', { typeof: true }],
      'no-undef-init': 'error',
      'no-undefined': 'off',
      'no-unused-vars': 'warn',

      // ==================== STYLISTIC ISSUES ====================
      'array-bracket-spacing': ['error', 'never'],
      'block-spacing': 'error',
      'brace-style': ['error', '1tbs', { allowSingleLine: true }],
      camelcase: 'off',
      'comma-dangle': ['error', 'only-multiline'],
      'comma-spacing': 'error',
      'comma-style': ['error', 'last'],
      'computed-property-spacing': ['error', 'never'],
      'consistent-this': ['error', 'self'],
      'eol-last': 'error',
      'func-call-spacing': 'error',
      'func-name-matching': 'warn',
      'func-names': ['warn', 'as-needed'],
      'function-paren-newline': ['error', 'consistent'],
      'implicit-arrow-linebreak': 'error',
      indent: ['error', 2, { SwitchCase: 1 }],
      'key-spacing': 'error',
      'keyword-spacing': 'error',
      'linebreak-style': ['error', 'windows'],
      'max-depth': ['warn', 4],
      'max-len': ['warn', { code: 120, ignoreUrls: true, ignoreStrings: true }],
      'max-nested-callbacks': ['warn', 3],
      'max-params': ['warn', 5],
      'new-cap': ['error', { newIsCap: true, capIsNew: true }],
      'new-parens': 'error',
      'no-array-constructor': 'error',
      'no-bitwise': 'error',
      'no-continue': 'off',
      'no-inline-comments': 'off',
      'no-mixed-operators': 'error',
      'no-mixed-spaces-and-tabs': 'error',
      'no-multiple-empty-lines': ['error', { max: 2, maxBOF: 1, maxEOF: 1 }],
      'no-new-object': 'error',
      'no-plusplus': 'off',
      'no-tabs': 'error',
      'no-trailing-spaces': 'error',
      'no-underscore-dangle': 'off',
      'object-curly-newline': ['error', { consistent: true }],
      'object-curly-spacing': ['error', 'always'],
      'object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
      'one-var': ['error', 'never'],
      'one-var-declaration-per-line': 'error',
      'operator-assignment': 'error',
      'operator-linebreak': ['error', 'before'],
      'padded-blocks': ['error', 'never'],
      'padding-line-between-statements': [
        'error',
        { blankLine: 'always', prev: 'directive', next: '*' },
        { blankLine: 'always', prev: '*', next: 'return' }
      ],
      'prefer-exponentiation-operator': 'warn',
      'prefer-object-spread': 'warn',
      quotes: ['error', 'single', { avoidEscape: true }],
      'quote-props': ['error', 'as-needed'],
      semi: ['error', 'always'],
      'semi-spacing': 'error',
      'semi-style': ['error', 'last'],
      'space-before-blocks': 'error',
      'space-before-function-paren': ['error', { anonymous: 'always', named: 'never', asyncArrow: 'always' }],
      'space-in-parens': ['error', 'never'],
      'space-infix-ops': 'error',
      'space-unary-ops': ['error', { words: true, nonwords: false }],
      'spaced-comment': ['error', 'always', { exceptions: ['-', '+', '*'] }],
      'switch-colon-spacing': 'error',
      'template-tag-spacing': 'error',
      'unicode-bom': ['error', 'never'],

      // ==================== ES6+ FEATURES ====================
      'arrow-body-style': ['error', 'as-needed'],
      'arrow-parens': ['error', 'as-needed'],
      'arrow-spacing': 'error',
      'constructor-super': 'error',
      'generator-star-spacing': ['error', { before: false, after: true }],
      'no-class-assign': 'error',
      'no-const-assign': 'error',
      'no-dupe-class-members': 'error',
      'no-this-before-super': 'error',
      'no-var': 'error',
      'object-shorthand': 'error',
      'prefer-arrow-callback': 'error',
      'prefer-const': 'error',
      'prefer-destructuring': 'warn',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'rest-spread-spacing': 'error',
      'sort-imports': 'off',
      'symbol-description': 'warn',
      'template-curly-spacing': ['error', 'never'],
      'yield-star-spacing': ['error', 'after'],
    },
  },
  {
    ignores: ['node_modules/', 'dist/', 'build/', '.git/', 'coverage/'],
  },
];
